import fs from 'fs';

const filePath = 'src/routes/index.tsx';
let content = fs.readFileSync(filePath, 'utf8');

if (!content.includes('valuatorCalculating')) {
  content = content.replace(
    'const [valuatorSubmitted, setValuatorSubmitted] = useState(false);',
    'const [valuatorSubmitted, setValuatorSubmitted] = useState(false);\n  const [valuatorCalculating, setValuatorCalculating] = useState(false);'
  );
}

const startMarker = '{/* ── VALORADOR DE INMUEBLES (BG SWAPPED TO BLUE - POINT 4) ── */}';
const endMarker = '{/* ── PROPERTIES GRID (REFERENCE IMAGE 1 STYLE) ── */}';

const startIndex = content.indexOf(startMarker);
const endIndex = content.indexOf(endMarker);

if (startIndex === -1 || endIndex === -1) {
  console.error('Markers not found!');
  process.exit(1);
}

const newValuatorSection = [
  '{/* ── VALORADOR DE INMUEBLES ── */}',
  '      <section id="valuator-form" className="relative overflow-hidden bg-[#e2e8f0] text-onyx py-10 md:py-20">',
  '        <div className="bg-[#005c99] rounded-[28px] md:rounded-[36px] shadow-2xl p-6 sm:p-10 md:p-16 mx-4 md:mx-auto max-w-[1300px] relative z-10 overflow-hidden text-white border border-white/10">',
  '',
  '          {/* Background shapes */}',
  '          <div className="absolute -top-32 -right-32 w-96 h-96 rounded-full bg-white/5 pointer-events-none" />',
  '          <div className="absolute -bottom-20 -left-20 w-64 h-64 rounded-full bg-white/5 pointer-events-none" />',
  '',
  '          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-16 items-center relative z-10">',
  '',
  '            {/* LEFT COLUMN */}',
  '            <div className="lg:col-span-7 flex flex-col justify-center">',
  '              <div className="flex items-center gap-3 mb-6">',
  '                <span className="inline-flex items-center gap-2 bg-white text-[#005c99] text-xs font-black tracking-wider uppercase px-5 py-2.5 rounded-full shadow-lg">',
  '                  <Home className="w-4 h-4 text-[#005c99] stroke-[2.5]" />',
  '                  {t.valorador.tag}',
  '                </span>',
  '              </div>',
  '',
  '              {/* Title with underline sitting strictly BELOW text */}',
  '              <h2 className="text-4xl sm:text-5xl lg:text-6xl font-black text-white mb-6 leading-[1.15] tracking-tight font-sans">',
  '                {t.valorador.title}{" "}',
  '                <span className="relative inline-block pb-3">',
  '                  <span className="relative z-10 text-white">{t.valorador.titleAccent}</span>',
  '                  <span className="absolute bottom-0 left-0 right-0 h-[6px] bg-[#38bdf8] rounded-full" />',
  '                </span>',
  '              </h2>',
  '',
  '              {/* Subtitle - Large and high contrast */}',
  '              <p className="text-white text-xl md:text-2xl lg:text-3xl font-bold leading-snug max-w-[580px] mb-10">',
  '                Obtén una estimación precisa del precio de mercado de tu vivienda en menos de <span className="text-white font-black">1 minuto</span> con datos reales de <span className="whitespace-nowrap text-white font-black">Santa Coloma de Gramenet</span>.',
  '              </p>',
  '',
  '              <div className="w-full max-w-xl">',
  '                {/* Form Box - Solid Navy Background (#0b214a) */}',
  '                <div className="w-full bg-[#0b214a] p-6 md:p-8 rounded-3xl border border-[#1e3a6e] shadow-xl">',
  '                  {/* Inputs Row */}',
  '                  <div className="flex flex-col sm:flex-row gap-4 mb-5">',
  '                    {/* Select Zona */}',
  '                    <div className="flex-1 bg-white rounded-2xl px-5 py-4 flex items-center justify-between shadow-md border border-slate-100">',
  '                      <div className="flex items-center gap-3 w-full">',
  '                        <MapPin className="w-5 h-5 text-[#005c99] shrink-0 stroke-[2.5]" />',
  '                        <select',
  '                          value={valuatorData.zona}',
  '                          onChange={e => setValuatorData(d => ({ ...d, zona: e.target.value }))}',
  '                          className="w-full bg-transparent border-0 p-0 text-base font-bold text-[#0f172a] focus:ring-0 appearance-none cursor-pointer outline-none font-sans"',
  '                        >',
  '                          <option value="" disabled hidden>{t.valorador.seleccionaZona}</option>',
  '                          {zonas.map(z => <option key={z} value={z}>{z}</option>)}',
  '                        </select>',
  '                      </div>',
  '                      <ChevronDown className="w-5 h-5 text-slate-400 shrink-0" />',
  '                    </div>',
  '',
  '                    {/* Input Superficie */}',
  '                    <div className="flex-1 bg-white rounded-2xl px-5 py-4 flex items-center gap-3 shadow-md border border-slate-100">',
  '                      <Home className="w-5 h-5 text-[#005c99] shrink-0 stroke-[2.5]" />',
  '                      <input',
  '                        type="number"',
  '                        placeholder={t.valorador.superficieLabel}',
  '                        value={valuatorData.metros}',
  '                        onChange={e => setValuatorData(d => ({ ...d, metros: e.target.value }))}',
  '                        className="w-full bg-transparent border-0 p-0 text-base font-bold text-[#0f172a] focus:ring-0 outline-none placeholder:text-slate-400 font-sans"',
  '                      />',
  '                    </div>',
  '                  </div>',
  '',
  '                  {/* Submit Button - Solid White with Dark Blue Text */}',
  '                  <button',
  '                    id="btn-calcular-valoracion"',
  '                    type="button"',
  '                    disabled={valuatorCalculating}',
  '                    onClick={() => {',
  '                      setValuatorCalculating(true);',
  '                      setTimeout(() => {',
  '                        const parsedMetros = parseInt(valuatorData.metros, 10) || 85;',
  '                        const preciosZona: Record<string, number> = {',
  '                          "Santa Rosa - Can Mariner": 2350,',
  '                          "Fondo": 2100,',
  '                          "Riu": 2200,',
  '                          "Centre": 2850,',
  '                          "El Raval": 2250,',
  '                          "Riera Alta - Llatí": 2150,',
  '                          "Singuerlín": 2400,',
  '                        };',
  '                        const precioM2 = preciosZona[valuatorData.zona] || 2400;',
  '                        const total = Math.round((parsedMetros * precioM2) / 1000) * 1000;',
  '                        const min = Math.round((total * 0.93) / 1000) * 1000;',
  '                        const max = Math.round((total * 1.07) / 1000) * 1000;',
  '                        ',
  '                        setLiveValuation({',
  '                          active: true,',
  '                          total,',
  '                          min,',
  '                          max,',
  '                          zonaName: valuatorData.zona || "Santa Coloma",',
  '                          metros: parsedMetros',
  '                        });',
  '                        setValuatorCalculating(false);',
  '                        ',
  '                        setTimeout(() => {',
  '                          const resultCard = document.getElementById("tarjeta-resultado-valoracion");',
  '                          if (resultCard) {',
  '                            resultCard.scrollIntoView({ behavior: "smooth", block: "center" });',
  '                          }',
  '                        }, 100);',
  '                      }, 600);',
  '                    }}',
  '                    className={`w-full font-extrabold text-base md:text-lg py-4 px-6 rounded-2xl transition-all duration-300 shadow-xl cursor-pointer flex items-center justify-center gap-3 mb-4 ${',
  '                      valuatorCalculating',
  '                        ? "bg-white/80 text-[#005c99] opacity-80 cursor-wait"',
  '                        : "bg-white hover:bg-slate-50 text-[#005c99] hover:shadow-2xl active:scale-[0.99]"',
  '                    }`}',
  '                  >',
  '                    {valuatorCalculating ? (',
  '                      <>',
  '                        <svg className="w-5 h-5 animate-spin text-[#005c99]" fill="none" viewBox="0 0 24 24">',
  '                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />',
  '                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />',
  '                        </svg>',
  '                        <span>Calculando...</span>',
  '                      </>',
  '                    ) : (',
  '                      <>',
  '                        <Home className="w-5 h-5 text-[#005c99]" />',
  '                        <span>{t.valorador.botonCalcular}</span>',
  '                        <ArrowRight className="w-5 h-5" />',
  '                      </>',
  '                    )}',
  '                  </button>',
  '',
  '                  {/* WhatsApp Direct Lead Button */}',
  '                  <a',
  '                    href="https://wa.me/34604259424?text=Hola,%20quisiera%20una%20valoraci%C3%B3n%20oficial%20gratuita%20de%20mi%20inmueble."',
  '                    target="_blank"',
  '                    rel="noopener noreferrer"',
  '                    className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs sm:text-sm py-3.5 px-4 rounded-xl transition-all duration-300 shadow-md flex items-center justify-center gap-2"',
  '                  >',
  '                    <MessageCircle className="w-4 h-4 fill-white" />',
  '                    <span>¿Quieres el informe oficial completo? Pídelo por WhatsApp</span>',
  '                  </a>',
  '                </div>',
  '',
  '                {/* Navigation Gray (#757989) Solid Badges */}',
  '                <div className="flex flex-wrap items-center gap-3 mt-6 text-white text-sm font-bold">',
  '                  <span className="flex items-center gap-2 bg-[#757989] border border-white/20 px-4 py-2.5 rounded-xl shadow-sm">',
  '                    <Check className="w-4 h-4 text-emerald-300 stroke-[3]" />',
  '                    {t.valorador.sinCompromiso}',
  '                  </span>',
  '                  <span className="flex items-center gap-2 bg-[#757989] border border-white/20 px-4 py-2.5 rounded-xl shadow-sm">',
  '                    <Star className="w-4 h-4 text-amber-300 fill-amber-300" />',
  '                    {t.valorador.resultadoInmediato}',
  '                  </span>',
  '                </div>',
  '              </div>',
  '            </div>',
  '',
  '            {/* RIGHT COLUMN: Animated Result Card */}',
  '            <div className="lg:col-span-5 flex items-center justify-center lg:justify-end" id="tarjeta-resultado-valoracion">',
  '              <AnimatePresence mode="wait">',
  '                {!liveValuation.active ? (',
  '                  /* Initial Placeholder Card */',
  '                  <motion.div',
  '                    key="placeholder"',
  '                    initial={{ opacity: 0, scale: 0.95 }}',
  '                    animate={{ opacity: 1, scale: 1 }}',
  '                    exit={{ opacity: 0, scale: 0.9, y: -20 }}',
  '                    transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}',
  '                    className="bg-[#0b214a] border-2 border-dashed border-[#38bdf8]/40 rounded-3xl w-full max-w-[420px] p-10 flex flex-col items-center justify-center text-center gap-5 min-h-[340px] shadow-xl"',
  '                  >',
  '                    <div className="w-20 h-20 rounded-full bg-[#005c99]/50 flex items-center justify-center border border-[#38bdf8]/30">',
  '                      <Home className="w-10 h-10 text-[#38bdf8]" />',
  '                    </div>',
  '                    <div>',
  '                      <p className="text-white font-black text-2xl mb-2">Tu valoración aparecerá aquí</p>',
  '                      <p className="text-slate-300 text-base font-medium leading-relaxed">Indica la zona y superficie en m² para ver el valor total estimado y precio por m² al instante.</p>',
  '                    </div>',
  '                    <div className="flex items-center gap-2 text-[#38bdf8] text-sm font-bold">',
  '                      <ArrowRight className="w-4 h-4 rotate-180" />',
  '                      Introduce los datos a la izquierda',
  '                    </div>',
  '                  </motion.div>',
  '                ) : (',
  '                  /* Dynamic Result Card with Reveal Animation */',
  '                  <motion.div',
  '                    key="resultado"',
  '                    initial={{ opacity: 0, scale: 0.88, y: 30 }}',
  '                    animate={{ opacity: 1, scale: 1, y: 0 }}',
  '                    transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}',
  '                    className="bg-white text-[#0f172a] rounded-3xl shadow-2xl w-full max-w-[420px] overflow-hidden border-4 border-[#38bdf8] ring-8 ring-[#38bdf8]/20"',
  '                  >',
  '                    {/* Header Strip - Dark Navy */}',
  '                    <div className="bg-[#0b214a] px-7 py-5 flex items-center justify-between">',
  '                      <div>',
  '                        <div className="text-xs font-black text-[#38bdf8] uppercase tracking-[0.2em] mb-1 font-sans flex items-center gap-1.5">',
  '                          <MapPin className="w-3.5 h-3.5" />',
  '                          {liveValuation.zonaName} &middot; {liveValuation.metros} m²',
  '                        </div>',
  '                        <div className="text-base font-bold text-white/80 uppercase tracking-widest font-sans">Resultado del cálculo</div>',
  '                      </div>',
  '                      <motion.div',
  '                        initial={{ scale: 0 }}',
  '                        animate={{ scale: 1 }}',
  '                        transition={{ delay: 0.2, type: "spring", stiffness: 400 }}',
  '                        className="w-10 h-10 rounded-full bg-emerald-500 flex items-center justify-center shadow-lg"',
  '                      >',
  '                        <Check className="w-5 h-5 text-white stroke-[3]" />',
  '                      </motion.div>',
  '                    </div>',
  '',
  '                    {/* Price Body */}',
  '                    <div className="px-7 py-6">',
  '                      {/* Main Price */}',
  '                      <motion.div',
  '                        initial={{ opacity: 0, y: 15 }}',
  '                        animate={{ opacity: 1, y: 0 }}',
  '                        transition={{ delay: 0.15, duration: 0.4 }}',
  '                        className="mb-4"',
  '                      >',
  '                        <div className="text-6xl md:text-7xl font-black text-[#0b214a] leading-none tracking-tight font-sans">',
  '                          {new Intl.NumberFormat("es-ES").format(liveValuation.total)}<span className="text-[#757989] text-4xl font-bold"> €</span>',
  '                        </div>',
  '                        <div className="text-base text-[#005c99] font-extrabold mt-3 font-sans bg-blue-50 px-3 py-1.5 rounded-lg inline-block border border-blue-100">',
  '                          {(liveValuation.total / liveValuation.metros).toFixed(0)} €/m² &middot; precio medio zona',
  '                        </div>',
  '                      </motion.div>',
  '',
  '                      {/* Range Box */}',
  '                      <motion.div',
  '                        initial={{ opacity: 0, x: -10 }}',
  '                        animate={{ opacity: 1, x: 0 }}',
  '                        transition={{ delay: 0.25, duration: 0.4 }}',
  '                        className="bg-[#f0f7ff] border border-[#bfdbfe] p-4 rounded-2xl mb-5"',
  '                      >',
  '                        <div className="text-xs font-black text-[#005c99] uppercase tracking-wider mb-1.5 font-sans">Rango estimado de mercado</div>',
  '                        <div className="text-2xl font-black text-[#0b214a] font-sans">',
  '                          {new Intl.NumberFormat("es-ES").format(liveValuation.min)}€',
  '                          <span className="text-[#757989] font-bold mx-2">–</span>',
  '                          {new Intl.NumberFormat("es-ES").format(liveValuation.max)}€',
  '                        </div>',
  '                      </motion.div>',
  '',
  '                      {/* Sparkline Chart */}',
  '                      <motion.div',
  '                        initial={{ opacity: 0 }}',
  '                        animate={{ opacity: 1 }}',
  '                        transition={{ delay: 0.35 }}',
  '                        className="mb-4 pt-4 border-t border-slate-100"',
  '                      >',
  '                        <div className="flex items-center justify-between text-xs font-black text-slate-700 mb-2 font-sans">',
  '                          <span>Tendencia precios Santa Coloma</span>',
  '                          <span className="text-emerald-600 flex items-center gap-1 font-sans bg-emerald-50 px-2 py-0.5 rounded-md"><TrendingUp className="w-3.5 h-3.5" /> +4.2%</span>',
  '                        </div>',
  '                        <div className="w-full h-12 relative">',
  '                          <svg className="w-full h-full overflow-visible" viewBox="0 0 200 40" fill="none">',
  '                            <defs>',
  '                              <linearGradient id="sparklineGradValuator" x1="0" y1="0" x2="0" y2="1">',
  '                                <stop offset="0%" stopColor="#005c99" stopOpacity="0.2" />',
  '                                <stop offset="100%" stopColor="#005c99" stopOpacity="0.0" />',
  '                              </linearGradient>',
  '                            </defs>',
  '                            <path d="M 0 35 L 0 30 Q 30 28 40 22 T 80 20 T 120 14 T 160 10 L 200 4 L 200 40 L 0 40 Z" fill="url(#sparklineGradValuator)" />',
  '                            <path d="M 0 30 Q 30 28 40 22 T 80 20 T 120 14 T 160 10 L 200 4" stroke="#005c99" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />',
  '                            <circle cx="200" cy="4" r="4" fill="#005c99" stroke="#ffffff" strokeWidth="2" />',
  '                          </svg>',
  '                        </div>',
  '                      </motion.div>',
  '',
  '                      <div className="flex items-center gap-2 text-xs font-bold text-slate-500 font-sans">',
  '                        <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />',
  '                        Estimación instantánea &middot; Santa Coloma de Gramenet',
  '                      </div>',
  '                    </div>',
  '                  </motion.div>',
  '                )}',
  '              </AnimatePresence>',
  '            </div>',
  '',
  '          </div>',
  '        </div>',
  '      </section>',
  ''
].join('\n');

content = content.slice(0, startIndex) + newValuatorSection + content.slice(endIndex);
fs.writeFileSync(filePath, content, 'utf8');
console.log('Successfully updated file!');
