/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as InmobiliariaSlugRouteImport } from './routes/inmobiliaria.$slug'

const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const InmobiliariaSlugRoute = InmobiliariaSlugRouteImport.update({
  id: '/inmobiliaria/$slug',
  path: '/inmobiliaria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/inmobiliaria/$slug': typeof InmobiliariaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/inmobiliaria/$slug': typeof InmobiliariaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/inmobiliaria/$slug': typeof InmobiliariaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/noticias'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/inmobiliaria/$slug'
    | '/noticias/$slug'
    | '/servicios/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/noticias'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/inmobiliaria/$slug'
    | '/noticias/$slug'
    | '/servicios/$slug'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/noticias'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/inmobiliaria/$slug'
    | '/noticias/$slug'
    | '/servicios/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BlogRoute: typeof BlogRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  InmobiliariaSlugRoute: typeof InmobiliariaSlugRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/inmobiliaria/$slug': {
      id: '/inmobiliaria/$slug'
      path: '/inmobiliaria/$slug'
      fullPath: '/inmobiliaria/$slug'
      preLoaderRoute: typeof InmobiliariaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BlogRoute: BlogRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  InmobiliariaSlugRoute: InmobiliariaSlugRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
