/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios_.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias_.$slug'
import { Route as InmobiliariaSlugRouteImport } from './routes/inmobiliaria_.$slug'

const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios_/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias_/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InmobiliariaSlugRoute = InmobiliariaSlugRouteImport.update({
  id: '/inmobiliaria_/$slug',
  path: '/inmobiliaria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/inmobiliaria/$slug': typeof InmobiliariaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/inmobiliaria/$slug': typeof InmobiliariaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/inmobiliaria_/$slug': typeof InmobiliariaSlugRoute
  '/noticias_/$slug': typeof NoticiasSlugRoute
  '/servicios_/$slug': typeof ServiciosSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso-legal'
    | '/blog'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/inmobiliaria/$slug'
    | '/noticias/$slug'
    | '/servicios/$slug'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aviso-legal'
    | '/blog'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/inmobiliaria/$slug'
    | '/noticias/$slug'
    | '/servicios/$slug'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso-legal'
    | '/blog'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/inmobiliaria_/$slug'
    | '/noticias_/$slug'
    | '/servicios_/$slug'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BlogRoute: typeof BlogRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  InmobiliariaSlugRoute: typeof InmobiliariaSlugRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios_/$slug': {
      id: '/servicios_/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias_/$slug': {
      id: '/noticias_/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inmobiliaria_/$slug': {
      id: '/inmobiliaria_/$slug'
      path: '/inmobiliaria/$slug'
      fullPath: '/inmobiliaria/$slug'
      preLoaderRoute: typeof InmobiliariaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BlogRoute: BlogRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  InmobiliariaSlugRoute: InmobiliariaSlugRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
