/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InmobiliariaSlugRouteImport } from './routes/inmobiliaria.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InmobiliariaSlugRoute = InmobiliariaSlugRouteImport.update({
  id: '/inmobiliaria/$slug',
  path: '/inmobiliaria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inmobiliaria/$slug': typeof InmobiliariaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inmobiliaria/$slug': typeof InmobiliariaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inmobiliaria/$slug': typeof InmobiliariaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inmobiliaria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inmobiliaria/$slug'
  id: '__root__' | '/' | '/inmobiliaria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InmobiliariaSlugRoute: typeof InmobiliariaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inmobiliaria/$slug': {
      id: '/inmobiliaria/$slug'
      path: '/inmobiliaria/$slug'
      fullPath: '/inmobiliaria/$slug'
      preLoaderRoute: typeof InmobiliariaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InmobiliariaSlugRoute: InmobiliariaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
